
meta_product_name: "Inventory Tracker"
meta_title: "Inventory Tracker - Your small business assistant"
meta_description: "Easily manage your inventory from anywhere, on mobile or desktop"
meta_image: "inventory_tracker.png"
